# THIS DOCKER COMPOSE FILE IS ONLY MEANT FOR DEVELOPMENT AND TESTING
---
services:
  postgresql:
    image: "postgres:17.2-alpine3.21"
    container_name: "postgresql"
    environment:
      POSTGRES_USER: "spring"
      POSTGRES_PASSWORD: "spring"
    ports:
      - "5432:5432"

  minio:
    image: "minio/minio:RELEASE.2025-02-07T23-21-09Z"
    container_name: "minio"
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
